// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXZ9Y0YumIz8o9hGgWCp7tXS21I0R_OXI',
    appId: '1:838755172479:web:75060b6a8f92ecc9dcff4a',
    messagingSenderId: '838755172479',
    projectId: 'assignmenttwo-5b7db',
    authDomain: 'assignmenttwo-5b7db.firebaseapp.com',
    storageBucket: 'assignmenttwo-5b7db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdAQS5NWs562T4QMHUQeJVrKGYU9kBPIM',
    appId: '1:838755172479:android:71688547a35ffef4dcff4a',
    messagingSenderId: '838755172479',
    projectId: 'assignmenttwo-5b7db',
    storageBucket: 'assignmenttwo-5b7db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANSuNH6hIraK8G0ofuCcCC8NnefVdZiU4',
    appId: '1:838755172479:ios:0954d8b01161c355dcff4a',
    messagingSenderId: '838755172479',
    projectId: 'assignmenttwo-5b7db',
    storageBucket: 'assignmenttwo-5b7db.appspot.com',
    iosBundleId: 'com.example.assignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANSuNH6hIraK8G0ofuCcCC8NnefVdZiU4',
    appId: '1:838755172479:ios:0954d8b01161c355dcff4a',
    messagingSenderId: '838755172479',
    projectId: 'assignmenttwo-5b7db',
    storageBucket: 'assignmenttwo-5b7db.appspot.com',
    iosBundleId: 'com.example.assignment2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXZ9Y0YumIz8o9hGgWCp7tXS21I0R_OXI',
    appId: '1:838755172479:web:48dea873a783b474dcff4a',
    messagingSenderId: '838755172479',
    projectId: 'assignmenttwo-5b7db',
    authDomain: 'assignmenttwo-5b7db.firebaseapp.com',
    storageBucket: 'assignmenttwo-5b7db.appspot.com',
  );
}
